version: '3.8'
services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=companions
      - MYSQL_ROOT_PASSWORD=companions
      - MYSQL_PASSWORD=companions
      - MYSQL_DATABASE=companions
  db-shadow:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_USER=companions
      - MYSQL_ROOT_PASSWORD=companions
      - MYSQL_PASSWORD=companions
      - MYSQL_DATABASE=companions
