name: pull-request
on: [pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: testing
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn
      - run: yarn lint
      - run: yarn test
